services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
  uptime-kuma:
    image: 'louislam/uptime-kuma:latest'
    container_name: uptime
    restart: unless-stopped
    ports:
      - 3001:3001

    volumes:
      - ./data:/app/data
    environment:
      - PUID=1000
      - PGID=1000


  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Winnipeg
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /media/public/Jellyfin:/config
      - /media/public/Jellyfin/Shows:/data/tvshows
      - /media/public/Jellyfin/Movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
